#include "acn.h"

@_VERSION ACNCFG_VERSION
@_OS_LINUX ACNCFG_OS_LINUX
@_NET_IPV4 ACNCFG_NET_IPV4
@_NET_IPV6 ACNCFG_NET_IPV6
@_MAX_IPADS ACNCFG_MAX_IPADS
@_LOCALIP_ANY ACNCFG_LOCALIP_ANY
@_MULTICAST_TTL ACNCFG_MULTICAST_TTL
@_JOIN_TX_GROUPS ACNCFG_JOIN_TX_GROUPS
@_RECEIVE_DEST_ADDRESS RECEIVE_DEST_ADDRESS


/*
@_ACNLOG_OFF ACNLOG_OFF
@_ACNLOG_SYSLOG ACNLOG_SYSLOG
@_ACNLOG_STDOUT ACNLOG_STDOUT
@_ACNLOG_STDERR ACNLOG_STDERR
@_LOG_OFF LOG_OFF
@_LOG_ON LOG_ON
@_ACNLOG ACNCFG_ACNLOG
@_LOGLEVEL ACNCFG_LOGLEVEL
@_LOGFUNCS ACNCFG_LOGFUNCS
*/

#if ACNCFG_ACNLOG == ACNLOG_OFF
@_LOGLEVEL off
#elif ACNCFG_ACNLOG == ACNLOG_SYSLOG
@_LOGLEVEL syslog
#elif ACNCFG_ACNLOG == ACNLOG_STDOUT
@_LOGLEVEL stdout
#elif ACNCFG_ACNLOG == ACNLOG_STDERR
@_LOGLEVEL stderr
#else
@_LOGLEVEL unknown (ACNCFG_ACNLOG)
#endif
#if ACNCFG_LOGFUNCS
@_LOGFUNCS on
#else
@_LOGFUNCS off
#endif

#if ACNCFG_LOG_RLP < 0
@_LOG_RLP off
#else
@_LOG_RLP on
#endif
#if ACNCFG_LOG_SDT < 0
@_LOG_SDT off
#else
@_LOG_SDT on
#endif
#if ACNCFG_LOG_NETX < 0
@_LOG_NETX off
#else
@_LOG_NETX on
#endif
#if ACNCFG_LOG_DMP < 0
@_LOG_DMP off
#else
@_LOG_DMP on
#endif
#if ACNCFG_LOG_DDL < 0
@_LOG_DDL off
#else
@_LOG_DDL on
#endif
#if ACNCFG_LOG_MISC < 0
@_LOG_MISC off
#else
@_LOG_MISC on
#endif
#if ACNCFG_LOG_EVLOOP < 0
@_LOG_EVLOOP off
#else
@_LOG_EVLOOP on
#endif
#if ACNCFG_LOG_E131 < 0
@_LOG_E131 off
#else
@_LOG_E131 on
#endif
#if ACNCFG_LOG_APP < 0
@_LOG_APP off
#else
@_LOG_APP on
#endif
#if ACNCFG_LOG_SESS < 0
@_LOG_SESS off
#else
@_LOG_SESS on
#endif

@_MARSHAL_INLINE ACNCFG_MARSHAL_INLINE
@_STRICT_CHECKS ACNCFG_STRICT_CHECKS
@_MULTI_COMPONENT ACNCFG_MULTI_COMPONENT
@_ACN_FCTN_SIZE ACN_FCTN_SIZE
@_ACN_UACN_SIZE ACN_UACN_SIZE

#if ACNCFG_UUIDS_RADIX
@_UUIDS_RADIX 1
#else
@_UUIDS_RADIX 0
#endif
#if ACNCFG_UUIDS_HASH
@_UUIDS_HASH 1
@_R_HASHBITS ACNCFG_R_HASHBITS
@_L_HASHBITS ACNCFG_L_HASHBITS
#else
@_UUIDS_HASH 0
#endif

@_EVLOOP ACNCFG_EVLOOP

#if ACNCFG_TIME_ms
@_TIME ms
#elif ACNCFG_TIME_POSIX_timeval
@_TIME timeval
#elif ACNCFG_TIME_POSIX_timespec
@_TIME timespec
#else
@_TIME unknown
#endif

#if ACNCFG_RLP
@_RLP 1
@_RLP_MAX_CLIENT_PROTOCOLS ACNCFG_RLP_MAX_CLIENT_PROTOCOLS
#if ACNCFG_RLP_MAX_CLIENT_PROTOCOLS == 1
#if ACNCFG_RLP_CLIENTPROTO == SDT_PROTOCOL_ID
@_RLP_CLIENTPROTO SDT
#elif ACNCFG_RLP_CLIENTPROTO == E131_PROTOCOL_ID
@_RLP_CLIENTPROTO E1.31
#else
@_RLP_CLIENTPROTO unknown (ACNCFG_RLP_CLIENTPROTO)
#endif
#endif
@_RLP_OPTIMIZE_PACK ACNCFG_RLP_OPTIMIZE_PACK
#else
@_RLP 0
#endif

#if ACNCFG_SDT
@_SDT 1
@_SDT_MAX_CLIENT_PROTOCOLS ACNCFG_SDT_MAX_CLIENT_PROTOCOLS
@_SDTRX_AUTOCALL ACNCFG_SDTRX_AUTOCALL
@_SDT_CHECK_ASSOC ACNCFG_SDT_CHECK_ASSOC
#if ACNCFG_SDT_MAX_CLIENT_PROTOCOLS == 1
@_SDT_CLIENTPROTO ACNCFG_SDT_CLIENTPROTO
#if ACNCFG_SDT_CLIENTPROTO == DMP_PROTOCOL_ID
@_SDT_CLIENTPROTO DMP
#else
@_SDT_CLIENTPROTO unknown (ACNCFG_SDT_CLIENTPROTO)
#endif
#endif
#else
@_SDT 0
#endif

#if ACNCFG_DMP
@_DMP 1
@_DMP_MAX_SUBSCRIPTIONS DMP_MAX_SUBSCRIPTIONS
@_DMPCOMP_CD ACNCFG_DMPCOMP_CD
@_DMPCOMP_C_ ACNCFG_DMPCOMP_C_
@_DMPCOMP__D ACNCFG_DMPCOMP__D

#if ACNCFG_DMPCOMP_Cx
@_DMPCOMP_Cx 1
#else
@_DMPCOMP_Cx 0
#endif
#if ACNCFG_DMPCOMP_xD
@_DMPCOMP_xD 1
#else
@_DMPCOMP_xD 0
#endif


@_DMPAD_MAXBYTES ACNCFG_DMPAD_MAXBYTES
@_DMPMAP_INDEX ACNCFG_DMPMAP_INDEX
@_DMPMAP_SEARCH ACNCFG_DMPMAP_SEARCH
@_DMPMAP_NONE ACNCFG_DMPMAP_NONE

#if ACNCFG_DMPON_SDT
@_DMPON_SDT 1
#else
@_DMPON_SDT 0
#endif
#if ACNCFG_DMPON_TCP
@_DMPON_TCP 1
#else
@_DMPON_TCP 0
#endif
#if ACNCFG_DMP_MULTITRANSPORT
@_DMP_MULTITRANSPORT 1
#else
@_DMP_MULTITRANSPORT 0
#endif

@_DMP_RMAXCXNS ACNCFG_DMP_RMAXCXNS
@_PROPEXT_FNS ACNCFG_PROPEXT_FNS
#else
@_DMP 0
#endif

#if ACNCFG_DDL
@_DDL 1
@_DDLACCESS_DMP ACNCFG_DDLACCESS_DMP
@_DDLACCESS_EPI26 ACNCFG_DDLACCESS_EPI26
@_DDL_BEHAVIORS ACNCFG_DDL_BEHAVIORS
@_DDL_IMMEDIATEPROPS ACNCFG_DDL_IMMEDIATEPROPS
@_DDL_STRINGS ACNCFG_DDL_STRINGS
@_DDL_MAXNEST ACNCFG_DDL_MAXNEST
@_STR_FOLDSPACE ACNCFG_STR_FOLDSPACE
@_DDL_MAXTEXT ACNCFG_DDL_MAXTEXT
@_MAPGEN ACNCFG_MAPGEN
#else
@_DDL 0
#endif

#if ACNCFG_E131
@_E131 1
@_E131_RX ACNCFG_E131_RX
@_E131_TX ACNCFG_E131_TX
@_E131MEM_MAXUNIVS E131MEM_MAXUNIVS
@_E131_ZSTART_ONLY ACNCFG_E131_ZSTART_ONLY
@_E131_IGNORE_PREVIEW ACNCFG_E131_IGNORE_PREVIEW
#else
@_E131 0
#endif
@_EPI10 ACNCFG_EPI10
@_EPI11 ACNCFG_EPI11
@_EPI12 ACNCFG_EPI12
@_EPI15 ACNCFG_EPI15
@_EPI16 ACNCFG_EPI16
@_EPI17 ACNCFG_EPI17
@_EPI18 ACNCFG_EPI18
@_EPI19 ACNCFG_EPI19
@_EPI20 ACNCFG_EPI20
@_EPI26 ACNCFG_EPI26
@_EPI29 ACNCFG_EPI29
